name: Organization Contribution Stats

on:
  schedule:
    - cron: '0 0 * * 1'  # Executa toda segunda-feira à meia-noite UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  fetch_stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Organization Members
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/DragaoLab/members" | jq -r '.[].login' > members.txt
          
          echo "Membros da organização:"
          cat members.txt

      - name: Fetch Contribution Stats
        run: |
          echo "## 🚀 Contribuições da DragãoLAB" > stats.md
          echo "" >> stats.md
          while read user; do
            echo "📌 **$user**" >> stats.md
            commits=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/search/commits?q=author:$user+org:DragaoLab" | jq '.total_count')
            prs=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/search/issues?q=author:$user+is:pr+org:DragaoLab" | jq '.total_count')
            issues=$(curl -s -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
              "https://api.github.com/search/issues?q=author:$user+is:issue+org:DragaoLab" | jq '.total_count')
            
            echo "🔹 Commits: $commits | 🔹 PRs: $prs | 🔹 Issues: $issues" >> stats.md
            echo "" >> stats.md
          done < members.txt

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add stats.md
          git commit -m "📊 Atualização automática das estatísticas"
          git push
