name: Update Stats
on:
  schedule:
    - cron: '0 0 * * *' # Roda diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub CLI
        run: echo "${{ secrets.TOKEN_GITHUB }}" | gh auth login --with-token

      - name: Coletar Estatísticas
        run: gh api orgs/DragaoLab/members --jq '.' > stats.md

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add stats.md
          git commit -m "Atualização automática de estatísticas"
          git push
